# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
version: 2

project_name: observer

before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: 'observer'
    binary: 'observer'
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    mod_timestamp: "{{ .CommitTimestamp }}"
    hooks:
      post:
        - cp observer.yml "{{dir .Path}}/observer.yml"
        - sed -i "s/0.0.0/{{ .Version }}/" "{{dir .Path}}/observer.yml"
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X main.treeState={{ .IsGitDirty }}

archives:
  - formats: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: zip

nfpms:
  - file_name_template: "{{ .ConventionalFileName }}"
    id: packages
    homepage: https://github.com/sbom-observer/observer-cli
    description: |-
      Generate SBOMs and optionally upload them to https://sbom.observer
    maintainer: Andreas Bielk <andreas@sbom.observer>
    license: Apache-2.0
    vendor: Bitfront AB
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/observer/copyright
        file_info:
          mode: 0644
    formats:
#      - apk
      - deb
      - rpm
#      - archlinux
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

sboms:
  - id: "cyclonedx"
    artifacts: binary
    documents:
      - "{{ .Binary }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}.cdx.json"
    cmd: 'observer'
    args: [ "fs", "-m", "$document", "{{ .ArtifactPath | abs | dir }}/observer.yml", "{{ .ArtifactPath | abs }}" ]

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^config:"
      - "^wip"

checksum:
  name_template: 'checksums.txt'

# .goreleaser.yaml
release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL or empty if its private hosted.
#  github:
#    owner: user
#    name: repo

  # If set to true, will not auto-publish the release.
  draft: true
  replace_existing_draft: true

  # If set to auto, will mark the release as not ready for production
  prerelease: auto

  # You can add extra pre-existing files to the release.
  # The filename on the release will be the last part of the path (base).
  # If another file with the same name exists, the last one found will be used.
  #
  # Templates: allowed
#  extra_files:
#    - glob: ./dist/bom.cdx.json
#    - glob: ./glob/**/to/**/file/**/*
#    - glob: ./glob/foo/to/bar/file/foobar/override_from_previous
#    - glob: ./single_file.txt
#      name_template: file.txt # note that this only works if glob matches 1 file only
